//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAYazOkulu.WebService.Test.ProductServiceClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private System.DateTime AddedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime AddedDate {
            get {
                return this.AddedDateField;
            }
            set {
                if ((this.AddedDateField.Equals(value) != true)) {
                    this.AddedDateField = value;
                    this.RaisePropertyChanged("AddedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductServiceClient.ProductServiceSoap")]
    public interface ProductServiceSoap {
        
        // CODEGEN: Generating message contract since element name product from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProduct", ReplyAction="*")]
        AAYazOkulu.WebService.Test.ProductServiceClient.AddProductResponse AddProduct(AAYazOkulu.WebService.Test.ProductServiceClient.AddProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<AAYazOkulu.WebService.Test.ProductServiceClient.AddProductResponse> AddProductAsync(AAYazOkulu.WebService.Test.ProductServiceClient.AddProductRequest request);
        
        // CODEGEN: Generating message contract since element name GetProductsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProducts", ReplyAction="*")]
        AAYazOkulu.WebService.Test.ProductServiceClient.GetProductsResponse GetProducts(AAYazOkulu.WebService.Test.ProductServiceClient.GetProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<AAYazOkulu.WebService.Test.ProductServiceClient.GetProductsResponse> GetProductsAsync(AAYazOkulu.WebService.Test.ProductServiceClient.GetProductsRequest request);
        
        // CODEGEN: Generating message contract since element name GetProductResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProduct", ReplyAction="*")]
        AAYazOkulu.WebService.Test.ProductServiceClient.GetProductResponse GetProduct(AAYazOkulu.WebService.Test.ProductServiceClient.GetProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<AAYazOkulu.WebService.Test.ProductServiceClient.GetProductResponse> GetProductAsync(AAYazOkulu.WebService.Test.ProductServiceClient.GetProductRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProduct", Namespace="http://tempuri.org/", Order=0)]
        public AAYazOkulu.WebService.Test.ProductServiceClient.AddProductRequestBody Body;
        
        public AddProductRequest() {
        }
        
        public AddProductRequest(AAYazOkulu.WebService.Test.ProductServiceClient.AddProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AAYazOkulu.WebService.Test.ProductServiceClient.Product product;
        
        public AddProductRequestBody() {
        }
        
        public AddProductRequestBody(AAYazOkulu.WebService.Test.ProductServiceClient.Product product) {
            this.product = product;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public AAYazOkulu.WebService.Test.ProductServiceClient.AddProductResponseBody Body;
        
        public AddProductResponse() {
        }
        
        public AddProductResponse(AAYazOkulu.WebService.Test.ProductServiceClient.AddProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AAYazOkulu.WebService.Test.ProductServiceClient.Product AddProductResult;
        
        public AddProductResponseBody() {
        }
        
        public AddProductResponseBody(AAYazOkulu.WebService.Test.ProductServiceClient.Product AddProductResult) {
            this.AddProductResult = AddProductResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProducts", Namespace="http://tempuri.org/", Order=0)]
        public AAYazOkulu.WebService.Test.ProductServiceClient.GetProductsRequestBody Body;
        
        public GetProductsRequest() {
        }
        
        public GetProductsRequest(AAYazOkulu.WebService.Test.ProductServiceClient.GetProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetProductsRequestBody {
        
        public GetProductsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public AAYazOkulu.WebService.Test.ProductServiceClient.GetProductsResponseBody Body;
        
        public GetProductsResponse() {
        }
        
        public GetProductsResponse(AAYazOkulu.WebService.Test.ProductServiceClient.GetProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AAYazOkulu.WebService.Test.ProductServiceClient.Product[] GetProductsResult;
        
        public GetProductsResponseBody() {
        }
        
        public GetProductsResponseBody(AAYazOkulu.WebService.Test.ProductServiceClient.Product[] GetProductsResult) {
            this.GetProductsResult = GetProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProduct", Namespace="http://tempuri.org/", Order=0)]
        public AAYazOkulu.WebService.Test.ProductServiceClient.GetProductRequestBody Body;
        
        public GetProductRequest() {
        }
        
        public GetProductRequest(AAYazOkulu.WebService.Test.ProductServiceClient.GetProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetProductRequestBody() {
        }
        
        public GetProductRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public AAYazOkulu.WebService.Test.ProductServiceClient.GetProductResponseBody Body;
        
        public GetProductResponse() {
        }
        
        public GetProductResponse(AAYazOkulu.WebService.Test.ProductServiceClient.GetProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AAYazOkulu.WebService.Test.ProductServiceClient.Product GetProductResult;
        
        public GetProductResponseBody() {
        }
        
        public GetProductResponseBody(AAYazOkulu.WebService.Test.ProductServiceClient.Product GetProductResult) {
            this.GetProductResult = GetProductResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductServiceSoapChannel : AAYazOkulu.WebService.Test.ProductServiceClient.ProductServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceSoapClient : System.ServiceModel.ClientBase<AAYazOkulu.WebService.Test.ProductServiceClient.ProductServiceSoap>, AAYazOkulu.WebService.Test.ProductServiceClient.ProductServiceSoap {
        
        public ProductServiceSoapClient() {
        }
        
        public ProductServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AAYazOkulu.WebService.Test.ProductServiceClient.AddProductResponse AAYazOkulu.WebService.Test.ProductServiceClient.ProductServiceSoap.AddProduct(AAYazOkulu.WebService.Test.ProductServiceClient.AddProductRequest request) {
            return base.Channel.AddProduct(request);
        }
        
        public AAYazOkulu.WebService.Test.ProductServiceClient.Product AddProduct(AAYazOkulu.WebService.Test.ProductServiceClient.Product product) {
            AAYazOkulu.WebService.Test.ProductServiceClient.AddProductRequest inValue = new AAYazOkulu.WebService.Test.ProductServiceClient.AddProductRequest();
            inValue.Body = new AAYazOkulu.WebService.Test.ProductServiceClient.AddProductRequestBody();
            inValue.Body.product = product;
            AAYazOkulu.WebService.Test.ProductServiceClient.AddProductResponse retVal = ((AAYazOkulu.WebService.Test.ProductServiceClient.ProductServiceSoap)(this)).AddProduct(inValue);
            return retVal.Body.AddProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AAYazOkulu.WebService.Test.ProductServiceClient.AddProductResponse> AAYazOkulu.WebService.Test.ProductServiceClient.ProductServiceSoap.AddProductAsync(AAYazOkulu.WebService.Test.ProductServiceClient.AddProductRequest request) {
            return base.Channel.AddProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<AAYazOkulu.WebService.Test.ProductServiceClient.AddProductResponse> AddProductAsync(AAYazOkulu.WebService.Test.ProductServiceClient.Product product) {
            AAYazOkulu.WebService.Test.ProductServiceClient.AddProductRequest inValue = new AAYazOkulu.WebService.Test.ProductServiceClient.AddProductRequest();
            inValue.Body = new AAYazOkulu.WebService.Test.ProductServiceClient.AddProductRequestBody();
            inValue.Body.product = product;
            return ((AAYazOkulu.WebService.Test.ProductServiceClient.ProductServiceSoap)(this)).AddProductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AAYazOkulu.WebService.Test.ProductServiceClient.GetProductsResponse AAYazOkulu.WebService.Test.ProductServiceClient.ProductServiceSoap.GetProducts(AAYazOkulu.WebService.Test.ProductServiceClient.GetProductsRequest request) {
            return base.Channel.GetProducts(request);
        }
        
        public AAYazOkulu.WebService.Test.ProductServiceClient.Product[] GetProducts() {
            AAYazOkulu.WebService.Test.ProductServiceClient.GetProductsRequest inValue = new AAYazOkulu.WebService.Test.ProductServiceClient.GetProductsRequest();
            inValue.Body = new AAYazOkulu.WebService.Test.ProductServiceClient.GetProductsRequestBody();
            AAYazOkulu.WebService.Test.ProductServiceClient.GetProductsResponse retVal = ((AAYazOkulu.WebService.Test.ProductServiceClient.ProductServiceSoap)(this)).GetProducts(inValue);
            return retVal.Body.GetProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AAYazOkulu.WebService.Test.ProductServiceClient.GetProductsResponse> AAYazOkulu.WebService.Test.ProductServiceClient.ProductServiceSoap.GetProductsAsync(AAYazOkulu.WebService.Test.ProductServiceClient.GetProductsRequest request) {
            return base.Channel.GetProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AAYazOkulu.WebService.Test.ProductServiceClient.GetProductsResponse> GetProductsAsync() {
            AAYazOkulu.WebService.Test.ProductServiceClient.GetProductsRequest inValue = new AAYazOkulu.WebService.Test.ProductServiceClient.GetProductsRequest();
            inValue.Body = new AAYazOkulu.WebService.Test.ProductServiceClient.GetProductsRequestBody();
            return ((AAYazOkulu.WebService.Test.ProductServiceClient.ProductServiceSoap)(this)).GetProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AAYazOkulu.WebService.Test.ProductServiceClient.GetProductResponse AAYazOkulu.WebService.Test.ProductServiceClient.ProductServiceSoap.GetProduct(AAYazOkulu.WebService.Test.ProductServiceClient.GetProductRequest request) {
            return base.Channel.GetProduct(request);
        }
        
        public AAYazOkulu.WebService.Test.ProductServiceClient.Product GetProduct(int id) {
            AAYazOkulu.WebService.Test.ProductServiceClient.GetProductRequest inValue = new AAYazOkulu.WebService.Test.ProductServiceClient.GetProductRequest();
            inValue.Body = new AAYazOkulu.WebService.Test.ProductServiceClient.GetProductRequestBody();
            inValue.Body.id = id;
            AAYazOkulu.WebService.Test.ProductServiceClient.GetProductResponse retVal = ((AAYazOkulu.WebService.Test.ProductServiceClient.ProductServiceSoap)(this)).GetProduct(inValue);
            return retVal.Body.GetProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AAYazOkulu.WebService.Test.ProductServiceClient.GetProductResponse> AAYazOkulu.WebService.Test.ProductServiceClient.ProductServiceSoap.GetProductAsync(AAYazOkulu.WebService.Test.ProductServiceClient.GetProductRequest request) {
            return base.Channel.GetProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<AAYazOkulu.WebService.Test.ProductServiceClient.GetProductResponse> GetProductAsync(int id) {
            AAYazOkulu.WebService.Test.ProductServiceClient.GetProductRequest inValue = new AAYazOkulu.WebService.Test.ProductServiceClient.GetProductRequest();
            inValue.Body = new AAYazOkulu.WebService.Test.ProductServiceClient.GetProductRequestBody();
            inValue.Body.id = id;
            return ((AAYazOkulu.WebService.Test.ProductServiceClient.ProductServiceSoap)(this)).GetProductAsync(inValue);
        }
    }
}
